//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EYEDYAS_TEST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_TB
    {
        public int PID { get; set; }
        public string PTITLE { get; set; }
        public string PIMAGE { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<int> STOCK { get; set; }
    }
}
